name: AIX360

channels:
    - anaconda
    - pytorch

dependencies:
    - python==3.6
    - pytorch
    - pip:
        - matplotlib
        - joblib>=0.11
        - scikit-learn>=0.21.2
        - cvxpy
        - cvxopt
        - Image
        - numpy>=1.16
        - pandas
        - scipy>=0.17
        - xport
        - scikit-image
        - requests
        - torchvision
        - keras
        - tensorflow
